import MainLoop from "@assets/images/menu_main_loop.png";
import ExceptionCatch from "@assets/images/menu_exception_catch.png";
import NightCompile from "@assets/images/menu_night_compile.png";
import Vanilla from "@assets/images/menu_vanilla_latte.png";
import Protocol from "@assets/images/menu_protocol.png";
import ColdBrew from "@assets/images/menu_Cold_brew.png";
import Menu01 from "@assets/images/menu01.png";
import Menu02 from "@assets/images/menu02.png";
import Menu03 from "@assets/images/menu03.png";
import Menu04 from "@assets/images/menu04.png";
import Menu05 from "@assets/images/menu05.png";
import Menu06 from "@assets/images/menu06.png";
import Menu07 from "@assets/images/menu07.png";
import Menu08 from "@assets/images/menu08.png";
import Menu09 from "@assets/images/menu09.png";
import Menu10 from "@assets/images/menu10.png";
import Menu11 from "@assets/images/menu11.png";
import Menu12 from "@assets/images/menu12.png";

export const menus = {
  "Code.C Signature": [
    {
      id: 1,
      name_en: "Blend.001 - Main Loop",
      name_ko: "메인 루프",
      desc: "매일의 루틴을 부드럽게 시작하는 가장 안정적인 커피 커맨드. 균형 잡힌 바디와 너츠 - 초콜릿 노트의 조화로 에스프레소부터 밀크 베리에이션까지 모두 잘 어울리는 블렌딩입니다.",
      image: MainLoop,
      info: {
        notes: "Chocolate, Nuts, Dried jujube",
        roast: "High Roasting",
        best: "Espresso, Latte",
      },
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 8,
        sodium: 7,
        fat: 0,
        sugar: 0,
        protein: 0,
        caffeine: 180,
      },
    },
    {
      id: 2,
      name_en: "Blend.C002 [Exception Catch]",
      name_ko: "예외 처리",
      desc: "비정상적인 매력, 예외를 포착하는 커피. 산뜻한 산미와 플로럴한 향이 어우러져 익숙함 속에 숨어 있는 새로움을 발견하게 합니다.",
      image: ExceptionCatch,
      info: {
        notes: "Orange Blossom, Jasmine, Lemon Peel, White Graffe",
        roast: "Cinnamon Roasting",
        best: "Pour Over, Drip, Iced Coffee",
      },
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 8,
        sodium: 7,
        fat: 0,
        sugar: 0,
        protein: 0,
        caffeine: 175,
      },
    },
    {
      id: 3,
      name_en: "Blend.C003 – Night Compile",
      name_ko: "나이트 컴파일",
      desc: "깊은 밤, 집중의 루틴을 완성하는 진한 코드. 묵직한 바디와 다크초콜릿의 농도가 하루의 끝을 매끄럽게 컴파일합니다.",
      image: NightCompile,
      info: {
        notes: "Dark chocolate, toffee nut, black sugar, and roast almond",
        roast: "Dark roasting",
        best: "Espresso, French Press, Latte",
      },
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 8,
        sodium: 7,
        fat: 0,
        sugar: 0,
        protein: 0,
        caffeine: 210,
      },
    },
    {
      id: 4,
      name_en: "Vanilla.C",
      name_ko: "바닐라.C",
      desc: "진짜 바닐라빈으로 설계된 순수한 단맛. 마다가스카르 바닐라빈을 직접 인퓨징해 부드럽고 자연스러운 향이 살아 있는 라떼입니다.",
      image: Vanilla,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 180,
        sodium: 0,
        fat: 5,
        sugar: 18,
        protein: 6,
        caffeine: 90,
      },
    },
    {
      id: 5,
      name_en: "Protocol: 36.5°",
      name_ko: "프로토콜: 36.5°",
      desc: "감정이 식지 않는 온도, 따뜻함을 데이터처럼 추출하다. 사람의 체온인 36.5℃로 저온 스티밍한 우유 위에 헤이즐넛 크림과 시나몬을 더한 따뜻한 라떼.",
      image: Protocol,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 190,
        sodium: 0,
        fat: 6,
        sugar: 17,
        protein: 7,
        caffeine: 95,
      },
    },
    {
      id: 6,
      name_en: "Cold Brew.Debug()",
      name_ko: "콜드브루.디버그()",
      desc: "무더운 로딩을 멈추는 디버그 커맨드. 12시간 이상 저온 침출로 완성된 클린하고 선명한 콜드브루 베이스.",
      image: ColdBrew,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 15,
        sodium: 0,
        fat: 0,
        sugar: 0,
        protein: 1,
        caffeine: 180,
      },
    },
  ],
  "Seasonal Selection": [
    {
      id: 7,
      name_en: "Nutty Fall Latte",
      name_ko: "너티 폴 라떼",
      desc: "따뜻한 너트 향과 고소한 시럽이 어우러진, 가을의 포근함을 담은 한 잔. 부드럽게 녹아드는 달콤함이 마음까지 채워줍니다.",
      image: Menu01,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 130,
        sodium: 95,
        fat: 4.2,
        sugar: 10,
        protein: 6,
        caffeine: 179,
      },
    },
    {
      id: 8,
      name_en: "Jeju Matcha Ice Cream",
      name_ko: "제주 말차 아이스크림",
      desc: "진한 제주말차 아이스크림에 고소한 단팥과 쫄깃한 인절미를 토핑해 식감과 맛, 비주얼을 동시에 잡은 디저트컵",
      image: Menu02,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 375,
        sodium: 120,
        fat: 4.8,
        sugar: 37,
        protein: 9,
        caffeine: 94,
      },
    },
    {
      id: 9,
      name_en: "Jeju Matcha Ice Cream Latte",
      name_ko: "제주 말차 아이스크림 라떼",
      desc: "제주말차 라떼에 진한 말차 아이스크림 토핑이 더해진 달콤한 아이스크림 라떼",
      image: Menu03,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 350,
        sodium: 65,
        fat: 9,
        sugar: 41,
        protein: 8,
        caffeine: 210,
      },
    },
  ],
  Essentials: [
    {
      id: 10,
      name_en: "Americano",
      name_ko: "아메리카노",
      desc: "Code.C 시그니처 블렌드로 추출한 에스프레소로 만든 부드럽고 깔끔한 가장 대중적인 커피 메뉴입니다.",
      image: Menu04,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 10,
        sodium: 0,
        fat: 0,
        sugar: 0,
        protein: 1,
        caffeine: 160,
      },
    },
    {
      id: 11,
      name_en: "Iced Cafe Oat",
      name_ko: "아이스 카페 오트",
      desc: "귀리를 통째로 갈아내어 만든 어메이징 오트로 만든 커피 음료",
      image: Menu05,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 145,
        sodium: 90,
        fat: 0.6,
        sugar: 3,
        protein: 2,
        caffeine: 225,
      },
    },
    {
      id: 12,
      name_en: "Iced Spanish Cafe Latte",
      name_ko: "아이스 스페니쉬 카페 라떼[연유]",
      desc: "폴 바셋 라떼와 연유의 단맛과 부드러움이 조화로운 라떼입니다.",
      image: Menu06,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 295,
        sodium: 100,
        fat: 11,
        sugar: 28,
        protein: 6,
        caffeine: 225,
      },
    },
  ],
  "Alternative Brews": [
    {
      id: 13,
      name_en: "Double Chocolate Frappe",
      name_ko: "더블 초콜릿 프라페",
      desc: "진한 초콜릿 맛을 우유의 풍미와 함께 부드럽고 시원하게 즐길 수 있는 초콜릿 프라페",
      image: Menu07,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 340,
        sodium: 150,
        fat: 7,
        sugar: 41,
        protein: 7,
        caffeine: 13,
      },
    },
    {
      id: 14,
      name_en: "Flat Peach Ade",
      name_ko: "납작 복숭아 에이드",
      desc: "복숭아 과육이 씹히는 달콤한 납작복숭아에이드",
      image: Menu08,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 190,
        sodium: 19,
        fat: 0,
        sugar: 30,
        protein: 1,
        caffeine: 0,
      },
    },
    {
      id: 15,
      name_en: "Jeju Lemon Ade",
      name_ko: "제주 레몬 에이드",
      desc: "청정 자연 제주 땅에서 자란 레몬을 착즙하여 레몬의 상큼한 맛을 담아낸 에이드입니다.",
      image: Menu09,
      nutrition: {
        serving: "Tall (355ml)",
        kcal: 175,
        sodium: 5,
        fat: 0,
        sugar: 42,
        protein: 0,
        caffeine: 0,
      },
    },
  ],
  Desserts: [
    {
      id: 16,
      name_en: "Matcha Castella",
      name_ko: "말차카스텔라",
      desc: "진한 노른자의 신선한 상하농원 계란과 제주산 말차의 풍미가 어우러진 촉촉한 정통 카스텔라",
      image: Menu10,
      nutrition: {
        serving: "250g",
        kcal: 725,
        sodium: 125,
        fat: 3,
        sugar: 100,
        protein: 17.5,
        caffeine: 0,
      },
    },
    {
      id: 17,
      name_en: "Tiramisu",
      name_ko: "티라미수",
      desc: "Code.C 커피 추출액을 사용하여 커피의 깊은 풍미를 지닌 시그니처 티라미수",
      image: Menu11,
      nutrition: {
        serving: "79g",
        kcal: 210,
        sodium: 45,
        fat: 9,
        sugar: 10,
        protein: 3,
        caffeine: 0,
      },
    },
    {
      id: 18,
      name_en: "Basque Cheese Cake",
      name_ko: "바스크 치즈 케이크",
      desc: "겉은 꾸덕하고 속은 촉촉하며 크림치즈의 풍미와 스모키한 캐러멜향이 조화로운 케이크",
      image: Menu12,
      nutrition: {
        serving: "135g",
        kcal: 451,
        sodium: 251,
        fat: 21,
        sugar: 29,
        protein: 8,
        caffeine: 0,
      },
    },
  ],
};
